exports.members = [{
  name: 'young',
  nick_name: 'young小哥哥',
  gender: 'male'
}, {
  name: 'alan',
  nick_name: 'alan小哥哥',
  gender: 'male'
}, {
  name: 'Dailer',
  nick_name: 'Dailer小哥哥',
  gender: 'male'
}, {
  name: 'fay',
  nick_name: 'fay小哥哥',
  gender: 'male'
}, {
  name: 'Frank.Qiu',
  nick_name: 'Frank小哥哥',
  gender: 'male'
}, {
  name: 'Guyi',
  nick_name: 'Guyi小哥哥',
  gender: 'male'
}, {
  name: 'imp',
  nick_name: '健哥哥',
  gender: 'male'
}, {
  name: 'Kira',
  nick_name: 'Kira小哥哥',
  gender: 'male'
}, {
  name: 'lei.wang',
  nick_name: '磊哥哥',
  gender: 'male'
}, {
  name: 'Teller',
  nick_name: 'Teller小哥哥',
  gender: 'male'
}, {
  name: 'windy',
  nick_name: 'Windy小哥哥',
  gender: 'male'
}, {
  name: 'Zhenfei.Li',
  nick_name: 'Zhenfei小哥哥',
  gender: 'male'
}, {
  name: 'Kobi',
  nick_name: 'Kobi小姐姐',
  gender: 'female'
}]