exports.members = [{
  name: 'young',
  nick_name: 'young小哥哥'
}, {
  name: 'alan',
  nick_name: 'alan小哥哥',
}, {
  name: 'andrew asa',
  nick_name: 'andrew小哥哥'
}, {
  name: 'Dailer',
  nick_name: 'dailer小哥哥'
}, {
  name: 'fay',
  nick_name: 'dailer小哥哥'
}, {
  name: 'Frank.Qiu',
  nick_name: 'frank小哥哥'
}, {
  name: 'Guyi',
  nick_name: 'guyi小哥哥'
}, {
  name: 'imp',
  nick_name: '健哥哥'
}, {
  name: 'kary',
  nick_name: 'kary小哥哥'
}, {
  name: 'Kira',
  nick_name: 'Kira小哥哥'
}, {
  name: 'lei.wang',
  nick_name: '磊哥哥'
}, {
  name: 'Teller',
  nick_name: 'teller小哥哥'
}, {
  name: 'windy',
  nick_name: 'windy小哥哥'
}, {
  name: 'Zhenfei.Li',
  nick_name: 'zhenfei小哥哥'
}]