exports.members = [{
  name: 'Sue.Wang',
  nick_name: 'Sue.Wang小姐姐',
  gender: 'female'
}, {
  name: 'Clarice',
  nick_name: 'Clarice小姐姐',
  gender: 'female'
}, {
  name: 'Cynthia',
  nick_name: 'Cynthia小姐姐',
  gender: 'female'
}, {
  name: 'Hongyu.Jiang',
  nick_name: 'Hongyu.Jiang小哥哥',
  gender: 'male'
}, {
  name: 'Katao',
  nick_name: 'Katao小哥哥',
  gender: 'male'
}, {
  name: 'Luoqiyuan',
  nick_name: 'Luoqiyuan小哥哥',
  gender: 'male'
}, {
  name: 'Mika.Sha',
  nick_name: 'Mika.Sha小哥哥',
  gender: 'male'
}, {
  name: 'Rye.Sigh',
  nick_name: 'Rye.Sigh小哥哥',
  gender: 'male'
}, {
  name: 'Wendy.Wu',
  nick_name: 'Wendy.Wu小姐姐',
  gender: 'female'
}]